dag_id: "adls_to_postgres_users"
description: "Ingestion des fichiers Parquet de test depuis ADLS/Azurite vers Postgres"
schedule: null

params:
  ID_PIPELINE: "adls_users_pipeline"
  USE_AZURITE: "true"                   # Passer à "false" en Prod Azure
  AZURE_CONN_ID: "azure_storage_default"
  POSTGRESQL_CIBLE: "postgres_cible"
  
  CONTENEUR_AZURE: "source-data"
  PATTERN_FICHIER: "users_test.parquet"
  
  SCHEMA_CIBLE: "dlt"
  TABLE_CIBLE: "users_test"
  STRATEGIE_ECRITURE: "replace"