dag_id: "postgres_to_adls__orders_items"
description: "Exportation configurable des tables Postgres vers ADLS/Azurite"
schedule: null

infrastructure:
  git_connection_id: "git-dlt"
  postgres_connection_id: "postgres_source"
  azure_connection_id: "azure_storage_default"
  use_azurite: true

pipeline:
  tables:
    - source:
        schema: "dlt"
        table: "orders"

      target:
        container: "target-data"
        dataset: "billetique"
        name: "ventes/commandes_export"
        format: "delta"
        write_strategy: "replace"
        use_partition: true
        partition_col: "expedition_date"

      execution:
        backend: "pyarrow"
        chunk_size: 500000